import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv('Homework1.csv')
print(df.head())
print(df['Temperature'].mean())
df.to_csv('result1.csv', sep=',', index_label='index')
df = pd.read_csv('Homework1.csv', parse_dates=['Date'], dayfirst=True)
print(df.head(5))
df.to_excel('result2.xlsx')
df = pd.read_csv('Homework2.csv', sep=';', parse_dates=['Date'], dayfirst=True)
print(df.head(5))
df.to_excel('result3.xlsx', sheet_name='MySheet')
df = pd.read_excel('Homework3.xlsx', parse_dates=['Date'])
print(df.head())
df.to_excel('Homework3.xlsx', sheet_name='MySheet', index=False)
df1 = pd.read_csv('Homework1.csv')
print(df1.head())
df2 = pd.read_csv('Homework4.csv')
print(df1.head())
df_merge = df1.merge(df2, on=['id'], how='outer')
print(df_merge.head())
df_merge.to_csv('result4.csv', sep=';', index=False)
df3 = pd.read_csv('Homework2.csv', sep=';', parse_dates=['Date'], dayfirst=True)
print(df3.head())
df4 = pd.read_excel('Homework5.xlsx', parse_dates=['Date'])
print(df4.head())
df_merge1 = df3.merge(df4, on=['Date'], how='outer')
print(df_merge1.head())
df_merge1.to_csv('result5.csv', sep='\t', index=False)
df_merge1['Temperature_C'] = round(((df_merge1['Temperature'] - 32) * 5 / 9), 2)
print(df_merge1.head())
df_merge1.to_csv('result6.csv', sep=';', index=False)

data = pd.read_csv('result6.csv', sep=';')
print(data.head())
plt.xlabel('Sales')
plt.ylabel('Temperature_C')
plt.scatter(x=data['Sales'], y=data['Temperature_C'])
